import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');
const Styles = StyleSheet.create({
  boxcontainer: {
    height: height * 0.23,
    width: width * 0.92,
    backgroundColor: 'black',
    marginHorizontal: 'auto',
    borderRadius: 30,
    alignItems: 'center',
  },
  rating: {
    backgroundColor: '#60B246',
    width: 40,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 30,
    height: 20,
  },
  ratingtext: {
    color: 'white',
    fontSize: 12,
    fontWeight: '500',
  },
  menutext: {
    borderWidth: 1,
    width: width * 0.7,
    borderRadius: 10,
    marginHorizontal: 'auto',
    padding: 10,
    borderColor: '#D6D6D6',
    fontSize: 16,
    fontWeight: '300',
    shadowColor: '#000',
    height: height * 0.055,
  },
  Menutext: {
    borderWidth: 1,
    width: width * 0.7,
    borderRadius: 10,
    marginHorizontal: 'auto',
    padding: 10,
    borderColor: '#D6D6D6',
    fontSize: 16,
    fontWeight: '300',
    shadowColor: '#000',
    height: height * 0.055,
  },
  list2: {
    borderWidth: 1,
    width: width * 0.2,
    height: height * 0.04,
    borderColor: '#D6D6D6',
    borderRadius: 5,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  list1: {
    borderWidth: 1,
    width: width * 0.15,
    height: height * 0.04,
    borderColor: '#D6D6D6',
    borderRadius: 5,
    marginHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  list3: {
    borderWidth: 1,
    width: width * 0.23,
    height: height * 0.04,
    borderColor: '#D6D6D6',
    borderRadius: 5,
    marginHorizontal: 10,

    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itembox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 16,
  },
  textbox: {
    width: width * 0.43,
    marginBottom: 20,

    padding: 20,
  },
  coverimage: {
    width: 140,
    height: 140,
    borderRadius: 10,
    resizeMode: 'cover',
    position: 'relative',
    marginTop: 10,
    alignSelf: 'center',
  },
  icon: {
    width: 10,
    height: 10,
    marginLeft: 10,
  },
  boldtext: {
    fontSize: 16,
    color: 'black',
    fontWeight: '400',
  },
  smalltext: {
    color: 'black',
    fontSize: 11,
    marginTop: 5,
    textAlign: 'center',
    fontWeight: '300',
  },
  headerbox: {
    flexDirection: 'row',
    borderTopWidth: 0.5,
    borderStyle: 'dashed',
    borderBottomWidth: 0.5,
    marginVertical: 20,
    paddingVertical: 10,
    borderColor: '#D6D6D6',
  },
  foodtext: {
    color: 'white',
    fontSize: 14,
    fontWeight: '300',
  },

  // rating2: {
  //   backgroundColor: '#60B246',
  //   width: 40,
  //   borderRadius: 5,
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   top: height * -0.13,
  //   marginLeft: 30,
  //   height: 20,
  // },
  // add: {
  //   width: 70,
  //   height: 25,
  //   borderWidth: 1,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   borderRadius: 5,
  //   borderColor: '#D6D6D6',
  //   top: -25,
  //   backgroundColor: 'white',
  //   zIndex: 1,
  // },
  // custom: {
  //   top: 14,
  //   fontSize: 7,
  //   fontWeight: '300',
  //   color: 'black',
  // },
  color: {
    fontSize: 12,
  },
  zingertext: {
    color: 'white',
    fontSize: 24,
    fontWeight: '600',
  },
  popup: {
    width: width * 1,
    height: height * 0.8,
    backgroundColor: '#202020',
    borderRadius: 15,
  },
  addbutton: {
    width: 70,
    height: 25,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    top: 0,
    elevation: 5,
  },
  addtext: {
    color: '#FA4A0C',
    fontSize: 16,
    fontWeight: '600',
  },
  addbox: {
    position: 'absolute',
    alignSelf: 'center',
    top: 135,
  },
  rating3: {
    backgroundColor: '#60B246',
    width: 40,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 30,
  },
  text1: {
    color: 'white',
    bottom: 35,
    margin: 10,
    fontSize: 18,
    fontWeight: '300',
    marginLeft: 30,
  },
  topbox: {
    width: width * 1,
    height: height * 0.3,
    backgroundColor: 'black',
  },
  topbox: {
    width: width * 1,
    height: height * 1,
    position: 'absolute',
    bottom: 200,
  },
  expandedPopup: {
    height: height * 0.9,
    backgroundColor: '#202020',
    bottom: height * 0.3,
    borderRadius: 15,
  },
  X: {
    width: 30,
    height: 30,
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    left: width * 0.8,
    bottom: height * 0.05,
  },
  custombox: {
    width: width * 0.8,
    height: height * 0.25,
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 5,
    margin: 15,
    marginHorizontal: 'auto',
    padding: 20,
  },
  custombox2: {
    width: width * 0.8,
    height: height * 0.15,
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 5,
    margin: 15,
    marginHorizontal: 'auto',
  },
  count: {
    width: 120,
    height: 50,
    backgroundColor: 'white',
    borderRadius: 5,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: 70,
  },
  Amount: {
    width: 160,
    height: 50,
    backgroundColor: 'white',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  size: {
    flexDirection: 'row',
    margin: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radiocircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderColor: '#FA4A0C',
    left: width * 0.6,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
  },
  radiobutton: {
    width: 12,
    height: 12,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: '#FA4A0C',
  },
  nonveg: {
    width: 10,
    height: 10,
  },
  text: {
    fontSize: 12,
    color: 'black',
    fontWeight: '300',
    marginTop: 20,
  },
  addbtn: {
    width: 100,
    height: 40,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    position: 'absolute',
    right: 30,
    top: 70,
  },
  add: {
    fontSize: 12,
    color: 'black',
    fontWeight: '300',
  },
  addbtn1: {
    width: 100,
    height: 40,
    backgroundColor: '#FA4A0C',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    right: 10,
  },
  pricetext: {
    color: 'black',
  },
  itemnamebox: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
});
export default Styles;
